//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Certification</summary>
	[PublishedContentModel("certification")]
	public partial class Certification : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "certification";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Certification(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Certification, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Classroom Content
		///</summary>
		[ImplementPropertyType("classroomContent")]
		public IHtmlString ClassroomContent
		{
			get { return this.GetPropertyValue<IHtmlString>("classroomContent"); }
		}

		///<summary>
		/// Classroom Costs
		///</summary>
		[ImplementPropertyType("classroomCosts")]
		public IHtmlString ClassroomCosts
		{
			get { return this.GetPropertyValue<IHtmlString>("classroomCosts"); }
		}

		///<summary>
		/// Classroom Format
		///</summary>
		[ImplementPropertyType("classroomFormat")]
		public IHtmlString ClassroomFormat
		{
			get { return this.GetPropertyValue<IHtmlString>("classroomFormat"); }
		}

		///<summary>
		/// Classroom Instructors
		///</summary>
		[ImplementPropertyType("classroomInstructors")]
		public IEnumerable<IPublishedContent> ClassroomInstructors
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("classroomInstructors"); }
		}

		///<summary>
		/// Common Content
		///</summary>
		[ImplementPropertyType("commonContent")]
		public IHtmlString CommonContent
		{
			get { return this.GetPropertyValue<IHtmlString>("commonContent"); }
		}

		///<summary>
		/// Course Highlights
		///</summary>
		[ImplementPropertyType("courseHighlights")]
		public IHtmlString CourseHighlights
		{
			get { return this.GetPropertyValue<IHtmlString>("courseHighlights"); }
		}

		///<summary>
		/// Featured Image
		///</summary>
		[ImplementPropertyType("featuredImage")]
		public IPublishedContent FeaturedImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("featuredImage"); }
		}

		///<summary>
		/// Have Questions
		///</summary>
		[ImplementPropertyType("haveQuestions")]
		public IHtmlString HaveQuestions
		{
			get { return this.GetPropertyValue<IHtmlString>("haveQuestions"); }
		}

		///<summary>
		/// Online Content
		///</summary>
		[ImplementPropertyType("onlineContent")]
		public IHtmlString OnlineContent
		{
			get { return this.GetPropertyValue<IHtmlString>("onlineContent"); }
		}

		///<summary>
		/// Online Costs
		///</summary>
		[ImplementPropertyType("onlineCosts")]
		public IHtmlString OnlineCosts
		{
			get { return this.GetPropertyValue<IHtmlString>("onlineCosts"); }
		}

		///<summary>
		/// Online Format
		///</summary>
		[ImplementPropertyType("onlineFormat")]
		public IHtmlString OnlineFormat
		{
			get { return this.GetPropertyValue<IHtmlString>("onlineFormat"); }
		}

		///<summary>
		/// Online Instructors
		///</summary>
		[ImplementPropertyType("onlineInstructors")]
		public IEnumerable<IPublishedContent> OnlineInstructors
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("onlineInstructors"); }
		}

		///<summary>
		/// Short Description: This field is the description displayed on the Certification List
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return this.GetPropertyValue<string>("shortDescription"); }
		}

		///<summary>
		/// Show Classroom Content: Select if classroom content is to be displayed for this course.
		///</summary>
		[ImplementPropertyType("showClassroomContent")]
		public bool ShowClassroomContent
		{
			get { return this.GetPropertyValue<bool>("showClassroomContent"); }
		}

		///<summary>
		/// Show Online Content: Select if online content is to be displayed for this course.
		///</summary>
		[ImplementPropertyType("showOnlineContent")]
		public bool ShowOnlineContent
		{
			get { return this.GetPropertyValue<bool>("showOnlineContent"); }
		}

		///<summary>
		/// Sponsors: List of all sponsors who's logos are to appear in certification.
		///</summary>
		[ImplementPropertyType("sponsors")]
		public IEnumerable<IPublishedContent> Sponsors
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sponsors"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Meta Robots
		///</summary>
		[ImplementPropertyType("metaRobots")]
		public object MetaRobots
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaRobots(this); }
		}

		///<summary>
		/// Redirects
		///</summary>
		[ImplementPropertyType("redirects")]
		public object Redirects
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetRedirects(this); }
		}

		///<summary>
		/// SEO Checker
		///</summary>
		[ImplementPropertyType("sEOChecker")]
		public SEOChecker.MVC.MetaData SEochecker
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetSEochecker(this); }
		}

		///<summary>
		/// Hide page from XML Sitemap
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// XMLSitemap
		///</summary>
		[ImplementPropertyType("xMLSitemap")]
		public object XMlsitemap
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetXMlsitemap(this); }
		}
	}
}
