//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1448 with alias "customPanels"
	/// <summary>Custom Panels</summary>
	public partial interface ICustomPanels : IPublishedContent
	{
		/// <summary>Background Image</summary>
		IPublishedContent Cp_BackgroundImage1 { get; }

		/// <summary>Background Image</summary>
		IPublishedContent Cp_BackgroundImage2 { get; }

		/// <summary>Background Image</summary>
		IPublishedContent Cp_BackgroundImage3 { get; }

		/// <summary>Description</summary>
		string Cp_Description1 { get; }

		/// <summary>Description</summary>
		string Cp_Description2 { get; }

		/// <summary>Description</summary>
		string Cp_Description3 { get; }

		/// <summary>Panel 1</summary>
		string Cp_Panel1 { get; }

		/// <summary>Panel 2</summary>
		string Cp_Panel2 { get; }

		/// <summary>Panel 3</summary>
		string Cp_Panel3 { get; }

		/// <summary>Quicklink</summary>
		IPublishedContent Cp_Quicklink1 { get; }

		/// <summary>Quicklink</summary>
		IPublishedContent Cp_Quicklink2 { get; }

		/// <summary>Quicklink</summary>
		IPublishedContent Cp_Quicklink3 { get; }

		/// <summary>Quicklink Title</summary>
		string Cp_QuicklinkTitle1 { get; }

		/// <summary>Quicklink Title</summary>
		string Cp_QuicklinkTitle2 { get; }

		/// <summary>Quicklink Title</summary>
		string Cp_QuicklinkTitle3 { get; }

		/// <summary>Title</summary>
		string Cp_Title1 { get; }

		/// <summary>Title</summary>
		string Cp_Title2 { get; }

		/// <summary>Title</summary>
		string Cp_Title3 { get; }
	}

	/// <summary>Custom Panels</summary>
	[PublishedContentModel("customPanels")]
	public partial class CustomPanels : PublishedContentModel, ICustomPanels
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customPanels";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomPanels(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomPanels, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Background Image
		///</summary>
		[ImplementPropertyType("cp_BackgroundImage1")]
		public IPublishedContent Cp_BackgroundImage1
		{
			get { return GetCp_BackgroundImage1(this); }
		}

		/// <summary>Static getter for Background Image</summary>
		public static IPublishedContent GetCp_BackgroundImage1(ICustomPanels that) { return that.GetPropertyValue<IPublishedContent>("cp_BackgroundImage1"); }

		///<summary>
		/// Background Image
		///</summary>
		[ImplementPropertyType("cp_BackgroundImage2")]
		public IPublishedContent Cp_BackgroundImage2
		{
			get { return GetCp_BackgroundImage2(this); }
		}

		/// <summary>Static getter for Background Image</summary>
		public static IPublishedContent GetCp_BackgroundImage2(ICustomPanels that) { return that.GetPropertyValue<IPublishedContent>("cp_BackgroundImage2"); }

		///<summary>
		/// Background Image
		///</summary>
		[ImplementPropertyType("cp_BackgroundImage3")]
		public IPublishedContent Cp_BackgroundImage3
		{
			get { return GetCp_BackgroundImage3(this); }
		}

		/// <summary>Static getter for Background Image</summary>
		public static IPublishedContent GetCp_BackgroundImage3(ICustomPanels that) { return that.GetPropertyValue<IPublishedContent>("cp_BackgroundImage3"); }

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("cp_Description1")]
		public string Cp_Description1
		{
			get { return GetCp_Description1(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetCp_Description1(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Description1"); }

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("cp_Description2")]
		public string Cp_Description2
		{
			get { return GetCp_Description2(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetCp_Description2(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Description2"); }

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("cp_Description3")]
		public string Cp_Description3
		{
			get { return GetCp_Description3(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetCp_Description3(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Description3"); }

		///<summary>
		/// Panel 1
		///</summary>
		[ImplementPropertyType("cp_Panel1")]
		public string Cp_Panel1
		{
			get { return GetCp_Panel1(this); }
		}

		/// <summary>Static getter for Panel 1</summary>
		public static string GetCp_Panel1(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Panel1"); }

		///<summary>
		/// Panel 2
		///</summary>
		[ImplementPropertyType("cp_Panel2")]
		public string Cp_Panel2
		{
			get { return GetCp_Panel2(this); }
		}

		/// <summary>Static getter for Panel 2</summary>
		public static string GetCp_Panel2(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Panel2"); }

		///<summary>
		/// Panel 3
		///</summary>
		[ImplementPropertyType("cp_Panel3")]
		public string Cp_Panel3
		{
			get { return GetCp_Panel3(this); }
		}

		/// <summary>Static getter for Panel 3</summary>
		public static string GetCp_Panel3(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Panel3"); }

		///<summary>
		/// Quicklink
		///</summary>
		[ImplementPropertyType("cp_Quicklink1")]
		public IPublishedContent Cp_Quicklink1
		{
			get { return GetCp_Quicklink1(this); }
		}

		/// <summary>Static getter for Quicklink</summary>
		public static IPublishedContent GetCp_Quicklink1(ICustomPanels that) { return that.GetPropertyValue<IPublishedContent>("cp_Quicklink1"); }

		///<summary>
		/// Quicklink
		///</summary>
		[ImplementPropertyType("cp_Quicklink2")]
		public IPublishedContent Cp_Quicklink2
		{
			get { return GetCp_Quicklink2(this); }
		}

		/// <summary>Static getter for Quicklink</summary>
		public static IPublishedContent GetCp_Quicklink2(ICustomPanels that) { return that.GetPropertyValue<IPublishedContent>("cp_Quicklink2"); }

		///<summary>
		/// Quicklink
		///</summary>
		[ImplementPropertyType("cp_Quicklink3")]
		public IPublishedContent Cp_Quicklink3
		{
			get { return GetCp_Quicklink3(this); }
		}

		/// <summary>Static getter for Quicklink</summary>
		public static IPublishedContent GetCp_Quicklink3(ICustomPanels that) { return that.GetPropertyValue<IPublishedContent>("cp_Quicklink3"); }

		///<summary>
		/// Quicklink Title
		///</summary>
		[ImplementPropertyType("cp_QuicklinkTitle1")]
		public string Cp_QuicklinkTitle1
		{
			get { return GetCp_QuicklinkTitle1(this); }
		}

		/// <summary>Static getter for Quicklink Title</summary>
		public static string GetCp_QuicklinkTitle1(ICustomPanels that) { return that.GetPropertyValue<string>("cp_QuicklinkTitle1"); }

		///<summary>
		/// Quicklink Title
		///</summary>
		[ImplementPropertyType("cp_QuicklinkTitle2")]
		public string Cp_QuicklinkTitle2
		{
			get { return GetCp_QuicklinkTitle2(this); }
		}

		/// <summary>Static getter for Quicklink Title</summary>
		public static string GetCp_QuicklinkTitle2(ICustomPanels that) { return that.GetPropertyValue<string>("cp_QuicklinkTitle2"); }

		///<summary>
		/// Quicklink Title
		///</summary>
		[ImplementPropertyType("cp_QuicklinkTitle3")]
		public string Cp_QuicklinkTitle3
		{
			get { return GetCp_QuicklinkTitle3(this); }
		}

		/// <summary>Static getter for Quicklink Title</summary>
		public static string GetCp_QuicklinkTitle3(ICustomPanels that) { return that.GetPropertyValue<string>("cp_QuicklinkTitle3"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("cp_Title1")]
		public string Cp_Title1
		{
			get { return GetCp_Title1(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetCp_Title1(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Title1"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("cp_Title2")]
		public string Cp_Title2
		{
			get { return GetCp_Title2(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetCp_Title2(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Title2"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("cp_Title3")]
		public string Cp_Title3
		{
			get { return GetCp_Title3(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetCp_Title3(ICustomPanels that) { return that.GetPropertyValue<string>("cp_Title3"); }
	}
}
