//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Events</summary>
	[PublishedContentModel("events")]
	public partial class Events : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "events";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Events(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Events, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// Address 1
		///</summary>
		[ImplementPropertyType("address1")]
		public string Address1
		{
			get { return this.GetPropertyValue<string>("address1"); }
		}

		///<summary>
		/// Address 2
		///</summary>
		[ImplementPropertyType("address2")]
		public string Address2
		{
			get { return this.GetPropertyValue<string>("address2"); }
		}

		///<summary>
		/// Chapter Affiliation
		///</summary>
		[ImplementPropertyType("chapterAffiliation")]
		public IEnumerable<IPublishedContent> ChapterAffiliation
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("chapterAffiliation"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Contact Info
		///</summary>
		[ImplementPropertyType("contactInfo")]
		public string ContactInfo
		{
			get { return this.GetPropertyValue<string>("contactInfo"); }
		}

		///<summary>
		/// Contact Members
		///</summary>
		[ImplementPropertyType("contactMembers")]
		public IEnumerable<IPublishedContent> ContactMembers
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("contactMembers"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}

		///<summary>
		/// Event Type
		///</summary>
		[ImplementPropertyType("eventType")]
		public IEnumerable<IPublishedContent> EventType
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("eventType"); }
		}

		///<summary>
		/// Featured Image: The "ListItemSquared" crop will be used for the selected image.
		///</summary>
		[ImplementPropertyType("featuredImage")]
		public IPublishedContent FeaturedImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("featuredImage"); }
		}

		///<summary>
		/// Location Name
		///</summary>
		[ImplementPropertyType("locationName")]
		public string LocationName
		{
			get { return this.GetPropertyValue<string>("locationName"); }
		}

		///<summary>
		/// Register Url: This option url will display a navigation button.
		///</summary>
		[ImplementPropertyType("registerUrl")]
		public string RegisterUrl
		{
			get { return this.GetPropertyValue<string>("registerUrl"); }
		}

		///<summary>
		/// Short Description
		///</summary>
		[ImplementPropertyType("shortDescription")]
		public string ShortDescription
		{
			get { return this.GetPropertyValue<string>("shortDescription"); }
		}

		///<summary>
		/// State
		///</summary>
		[ImplementPropertyType("state")]
		public string State
		{
			get { return this.GetPropertyValue<string>("state"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}

		///<summary>
		/// Zip
		///</summary>
		[ImplementPropertyType("zip")]
		public string Zip
		{
			get { return this.GetPropertyValue<string>("zip"); }
		}
	}
}
