//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 65689 with alias "maintenance"
	/// <summary>Maintenance</summary>
	public partial interface IMaintenance : IPublishedContent
	{
		/// <summary>Disable Login</summary>
		object DisableLogin { get; }
	}

	/// <summary>Maintenance</summary>
	[PublishedContentModel("maintenance")]
	public partial class Maintenance : PublishedContentModel, IMaintenance
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "maintenance";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Maintenance(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Maintenance, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disable Login: Used when the site is to remain on but the SSO is under maintenance.
		///</summary>
		[ImplementPropertyType("disableLogin")]
		public object DisableLogin
		{
			get { return GetDisableLogin(this); }
		}

		/// <summary>Static getter for Disable Login</summary>
		public static object GetDisableLogin(IMaintenance that) { return that.GetPropertyValue("disableLogin"); }
	}
}
