//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1769 with alias "personalNotes"
	/// <summary>Personal Notes</summary>
	public partial interface IPersonalNotes : IPublishedContent
	{
		/// <summary>Notes</summary>
		IHtmlString Notes { get; }
	}

	/// <summary>Personal Notes</summary>
	[PublishedContentModel("personalNotes")]
	public partial class PersonalNotes : PublishedContentModel, IPersonalNotes
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "personalNotes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PersonalNotes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PersonalNotes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Notes
		///</summary>
		[ImplementPropertyType("notes")]
		public IHtmlString Notes
		{
			get { return GetNotes(this); }
		}

		/// <summary>Static getter for Notes</summary>
		public static IHtmlString GetNotes(IPersonalNotes that) { return that.GetPropertyValue<IHtmlString>("notes"); }
	}
}
