//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Podcast</summary>
	[PublishedContentModel("podcast")]
	public partial class Podcast : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "podcast";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Podcast(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Podcast, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Author
		///</summary>
		[ImplementPropertyType("author")]
		public object Author
		{
			get { return this.GetPropertyValue("author"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return this.GetPropertyValue<IHtmlString>("content"); }
		}

		///<summary>
		/// Featured Image
		///</summary>
		[ImplementPropertyType("featuredImage")]
		public string FeaturedImage
		{
			get { return this.GetPropertyValue<string>("featuredImage"); }
		}

		///<summary>
		/// Include in RSS Feed
		///</summary>
		[ImplementPropertyType("includeInRSSFeed")]
		public bool IncludeInRssfeed
		{
			get { return this.GetPropertyValue<bool>("includeInRSSFeed"); }
		}

		///<summary>
		/// Navigation Title: This is used in feature widgets. Example: Homepage
		///</summary>
		[ImplementPropertyType("navigationTitle")]
		public string NavigationTitle
		{
			get { return this.GetPropertyValue<string>("navigationTitle"); }
		}

		///<summary>
		/// Podcast Audio
		///</summary>
		[ImplementPropertyType("podcastAudio")]
		public IPublishedContent PodcastAudio
		{
			get { return this.GetPropertyValue<IPublishedContent>("podcastAudio"); }
		}

		///<summary>
		/// Post Date
		///</summary>
		[ImplementPropertyType("postDate")]
		public DateTime PostDate
		{
			get { return this.GetPropertyValue<DateTime>("postDate"); }
		}

		///<summary>
		/// Publish Date
		///</summary>
		[ImplementPropertyType("publishDate")]
		public DateTime PublishDate
		{
			get { return this.GetPropertyValue<DateTime>("publishDate"); }
		}

		///<summary>
		/// RSS Description
		///</summary>
		[ImplementPropertyType("rssDescription")]
		public string RssDescription
		{
			get { return this.GetPropertyValue<string>("rssDescription"); }
		}

		///<summary>
		/// RSS Title
		///</summary>
		[ImplementPropertyType("rssTitle")]
		public string RssTitle
		{
			get { return this.GetPropertyValue<string>("rssTitle"); }
		}

		///<summary>
		/// Summary
		///</summary>
		[ImplementPropertyType("summary")]
		public string Summary
		{
			get { return this.GetPropertyValue<string>("summary"); }
		}

		///<summary>
		/// Tags
		///</summary>
		[ImplementPropertyType("tags")]
		public IEnumerable<IPublishedContent> Tags
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("tags"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}
}
