//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1363 with alias "quicklinkPanels"
	/// <summary>Quicklink Panels</summary>
	public partial interface IQuicklinkPanels : IPublishedContent
	{
		/// <summary>Quicklinks</summary>
		IEnumerable<IPublishedContent> Qlp_quicklinks { get; }
	}

	/// <summary>Quicklink Panels</summary>
	[PublishedContentModel("quicklinkPanels")]
	public partial class QuicklinkPanels : PublishedContentModel, IQuicklinkPanels
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "quicklinkPanels";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public QuicklinkPanels(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuicklinkPanels, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Quicklinks: Select existing items from “Content } Data } Lower Quick Links”.  If this selection is left empty, the Lower Quick Links panel will be hidden. Best viewed when an even number of Lower Quick Links are selected.
		///</summary>
		[ImplementPropertyType("qlp_quicklinks")]
		public IEnumerable<IPublishedContent> Qlp_quicklinks
		{
			get { return GetQlp_quicklinks(this); }
		}

		/// <summary>Static getter for Quicklinks</summary>
		public static IEnumerable<IPublishedContent> GetQlp_quicklinks(IQuicklinkPanels that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("qlp_quicklinks"); }
	}
}
