//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1352 with alias "quoteBanner"
	/// <summary>Quote Banner</summary>
	public partial interface IQuoteBanner : IPublishedContent
	{
		/// <summary>Drop Shadow</summary>
		object DropShadow { get; }

		/// <summary>Background Image</summary>
		IPublishedContent Qb_backgroundImage { get; }

		/// <summary>Call to Action Link</summary>
		IPublishedContent Qb_callToActionLink { get; }

		/// <summary>Call to Action Text</summary>
		string Qb_callToActionText { get; }

		/// <summary>Subtitle</summary>
		string Qb_subtitle { get; }

		/// <summary>Text Alignment</summary>
		object Qb_textAlignment { get; }

		/// <summary>Title</summary>
		string Qb_title { get; }

		/// <summary>Use Native Dimensions</summary>
		bool UseNativeDimensions { get; }
	}

	/// <summary>Quote Banner</summary>
	[PublishedContentModel("quoteBanner")]
	public partial class QuoteBanner : PublishedContentModel, IQuoteBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "quoteBanner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public QuoteBanner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<QuoteBanner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Drop Shadow
		///</summary>
		[ImplementPropertyType("dropShadow")]
		public object DropShadow
		{
			get { return GetDropShadow(this); }
		}

		/// <summary>Static getter for Drop Shadow</summary>
		public static object GetDropShadow(IQuoteBanner that) { return that.GetPropertyValue("dropShadow"); }

		///<summary>
		/// Background Image: *Required
		///</summary>
		[ImplementPropertyType("qb_backgroundImage")]
		public IPublishedContent Qb_backgroundImage
		{
			get { return GetQb_backgroundImage(this); }
		}

		/// <summary>Static getter for Background Image</summary>
		public static IPublishedContent GetQb_backgroundImage(IQuoteBanner that) { return that.GetPropertyValue<IPublishedContent>("qb_backgroundImage"); }

		///<summary>
		/// Call to Action Link: *Optional: CTA Text & Link are both required to show button.
		///</summary>
		[ImplementPropertyType("qb_callToActionLink")]
		public IPublishedContent Qb_callToActionLink
		{
			get { return GetQb_callToActionLink(this); }
		}

		/// <summary>Static getter for Call to Action Link</summary>
		public static IPublishedContent GetQb_callToActionLink(IQuoteBanner that) { return that.GetPropertyValue<IPublishedContent>("qb_callToActionLink"); }

		///<summary>
		/// Call to Action Text: *Optional: CTA Text & Link are both required to show button.
		///</summary>
		[ImplementPropertyType("qb_callToActionText")]
		public string Qb_callToActionText
		{
			get { return GetQb_callToActionText(this); }
		}

		/// <summary>Static getter for Call to Action Text</summary>
		public static string GetQb_callToActionText(IQuoteBanner that) { return that.GetPropertyValue<string>("qb_callToActionText"); }

		///<summary>
		/// Subtitle
		///</summary>
		[ImplementPropertyType("qb_subtitle")]
		public string Qb_subtitle
		{
			get { return GetQb_subtitle(this); }
		}

		/// <summary>Static getter for Subtitle</summary>
		public static string GetQb_subtitle(IQuoteBanner that) { return that.GetPropertyValue<string>("qb_subtitle"); }

		///<summary>
		/// Text Alignment: Default is left aligned.
		///</summary>
		[ImplementPropertyType("qb_textAlignment")]
		public object Qb_textAlignment
		{
			get { return GetQb_textAlignment(this); }
		}

		/// <summary>Static getter for Text Alignment</summary>
		public static object GetQb_textAlignment(IQuoteBanner that) { return that.GetPropertyValue("qb_textAlignment"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("qb_title")]
		public string Qb_title
		{
			get { return GetQb_title(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetQb_title(IQuoteBanner that) { return that.GetPropertyValue<string>("qb_title"); }

		///<summary>
		/// Use Native Dimensions: Selecting this option will remove all parameters from the background image and use it's native style.
		///</summary>
		[ImplementPropertyType("useNativeDimensions")]
		public bool UseNativeDimensions
		{
			get { return GetUseNativeDimensions(this); }
		}

		/// <summary>Static getter for Use Native Dimensions</summary>
		public static bool GetUseNativeDimensions(IQuoteBanner that) { return that.GetPropertyValue<bool>("useNativeDimensions"); }
	}
}
