//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1410 with alias "rotatingBanner"
	/// <summary>Rotating Banner</summary>
	public partial interface IRotatingBanner : IPublishedContent
	{
		/// <summary>Rotating Banners</summary>
		IEnumerable<IPublishedContent> RotatingBanners { get; }
	}

	/// <summary>Rotating Banner</summary>
	[PublishedContentModel("rotatingBanner")]
	public partial class RotatingBanner : PublishedContentModel, IRotatingBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "rotatingBanner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public RotatingBanner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<RotatingBanner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Rotating Banners: Select 4 banners to display in the rotator.
		///</summary>
		[ImplementPropertyType("rotatingBanners")]
		public IEnumerable<IPublishedContent> RotatingBanners
		{
			get { return GetRotatingBanners(this); }
		}

		/// <summary>Static getter for Rotating Banners</summary>
		public static IEnumerable<IPublishedContent> GetRotatingBanners(IRotatingBanner that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("rotatingBanners"); }
	}
}
