//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 2080 with alias "sEO"
	/// <summary>SEO</summary>
	public partial interface ISEO : IPublishedContent
	{
		/// <summary>Meta Robots</summary>
		object MetaRobots { get; }

		/// <summary>Redirects</summary>
		object Redirects { get; }

		/// <summary>SEO Checker</summary>
		SEOChecker.MVC.MetaData SEochecker { get; }

		/// <summary>Hide page from XML Sitemap</summary>
		bool UmbracoNaviHide { get; }

		/// <summary>XMLSitemap</summary>
		object XMlsitemap { get; }
	}

	/// <summary>SEO</summary>
	[PublishedContentModel("sEO")]
	public partial class SEO : PublishedContentModel, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sEO";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SEO(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SEO, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Robots
		///</summary>
		[ImplementPropertyType("metaRobots")]
		public object MetaRobots
		{
			get { return GetMetaRobots(this); }
		}

		/// <summary>Static getter for Meta Robots</summary>
		public static object GetMetaRobots(ISEO that) { return that.GetPropertyValue("metaRobots"); }

		///<summary>
		/// Redirects
		///</summary>
		[ImplementPropertyType("redirects")]
		public object Redirects
		{
			get { return GetRedirects(this); }
		}

		/// <summary>Static getter for Redirects</summary>
		public static object GetRedirects(ISEO that) { return that.GetPropertyValue("redirects"); }

		///<summary>
		/// SEO Checker
		///</summary>
		[ImplementPropertyType("sEOChecker")]
		public SEOChecker.MVC.MetaData SEochecker
		{
			get { return GetSEochecker(this); }
		}

		/// <summary>Static getter for SEO Checker</summary>
		public static SEOChecker.MVC.MetaData GetSEochecker(ISEO that) { return that.GetPropertyValue<SEOChecker.MVC.MetaData>("sEOChecker"); }

		///<summary>
		/// Hide page from XML Sitemap
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Hide page from XML Sitemap</summary>
		public static bool GetUmbracoNaviHide(ISEO that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }

		///<summary>
		/// XMLSitemap
		///</summary>
		[ImplementPropertyType("xMLSitemap")]
		public object XMlsitemap
		{
			get { return GetXMlsitemap(this); }
		}

		/// <summary>Static getter for XMLSitemap</summary>
		public static object GetXMlsitemap(ISEO that) { return that.GetPropertyValue("xMLSitemap"); }
	}
}
