//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1473 with alias "simpleBanner"
	/// <summary>Simple Banner</summary>
	public partial interface ISimpleBanner : IPublishedContent
	{
		/// <summary>Drop Shadow</summary>
		object DropShadow { get; }

		/// <summary>Background Image</summary>
		IPublishedContent Sb_backgroundImage { get; }

		/// <summary>Subtitle</summary>
		string Sb_subtitle { get; }

		/// <summary>Title</summary>
		string Sb_title { get; }

		/// <summary>Use Native Dimensions</summary>
		bool UseNativeDimensions { get; }
	}

	/// <summary>Simple Banner</summary>
	[PublishedContentModel("simpleBanner")]
	public partial class SimpleBanner : PublishedContentModel, ISimpleBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "simpleBanner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SimpleBanner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SimpleBanner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Drop Shadow
		///</summary>
		[ImplementPropertyType("dropShadow")]
		public object DropShadow
		{
			get { return GetDropShadow(this); }
		}

		/// <summary>Static getter for Drop Shadow</summary>
		public static object GetDropShadow(ISimpleBanner that) { return that.GetPropertyValue("dropShadow"); }

		///<summary>
		/// Background Image: The "FullBanner" or "NarrowBanner" crop will be used for the selected image.  If left blank, the simple banner will not be displayed.
		///</summary>
		[ImplementPropertyType("sb_backgroundImage")]
		public IPublishedContent Sb_backgroundImage
		{
			get { return GetSb_backgroundImage(this); }
		}

		/// <summary>Static getter for Background Image</summary>
		public static IPublishedContent GetSb_backgroundImage(ISimpleBanner that) { return that.GetPropertyValue<IPublishedContent>("sb_backgroundImage"); }

		///<summary>
		/// Subtitle
		///</summary>
		[ImplementPropertyType("sb_subtitle")]
		public string Sb_subtitle
		{
			get { return GetSb_subtitle(this); }
		}

		/// <summary>Static getter for Subtitle</summary>
		public static string GetSb_subtitle(ISimpleBanner that) { return that.GetPropertyValue<string>("sb_subtitle"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("sb_title")]
		public string Sb_title
		{
			get { return GetSb_title(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetSb_title(ISimpleBanner that) { return that.GetPropertyValue<string>("sb_title"); }

		///<summary>
		/// Use Native Dimensions: Selecting this option will remove all parameters from the background image and use it's native style.
		///</summary>
		[ImplementPropertyType("useNativeDimensions")]
		public bool UseNativeDimensions
		{
			get { return GetUseNativeDimensions(this); }
		}

		/// <summary>Static getter for Use Native Dimensions</summary>
		public static bool GetUseNativeDimensions(ISimpleBanner that) { return that.GetPropertyValue<bool>("useNativeDimensions"); }
	}
}
