//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 17140 with alias "socialFollowUs"
	/// <summary>Social-Follow-Us</summary>
	public partial interface ISocialFollowUs : IPublishedContent
	{
		/// <summary>B2B</summary>
		string B2BfollowUsurl { get; }

		/// <summary>Facebook</summary>
		string FacebookFollowUsurl { get; }

		/// <summary>Follow US URLs</summary>
		string FollowUsurls { get; }

		/// <summary>LinkedIn</summary>
		string LinkedInFollowUsurl { get; }

		/// <summary>Twitter</summary>
		string TwitterFollowUsurl { get; }

		/// <summary>YouTube</summary>
		string YouTubeFollowUsurl { get; }
	}

	/// <summary>Social-Follow-Us</summary>
	[PublishedContentModel("socialFollowUs")]
	public partial class SocialFollowUs : PublishedContentModel, ISocialFollowUs
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "socialFollowUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialFollowUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialFollowUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// B2B: B2B follow us URL
		///</summary>
		[ImplementPropertyType("b2BFollowUSURL")]
		public string B2BfollowUsurl
		{
			get { return GetB2BfollowUsurl(this); }
		}

		/// <summary>Static getter for B2B</summary>
		public static string GetB2BfollowUsurl(ISocialFollowUs that) { return that.GetPropertyValue<string>("b2BFollowUSURL"); }

		///<summary>
		/// Facebook: Facebook follow us URL
		///</summary>
		[ImplementPropertyType("facebookFollowUSURL")]
		public string FacebookFollowUsurl
		{
			get { return GetFacebookFollowUsurl(this); }
		}

		/// <summary>Static getter for Facebook</summary>
		public static string GetFacebookFollowUsurl(ISocialFollowUs that) { return that.GetPropertyValue<string>("facebookFollowUSURL"); }

		///<summary>
		/// Follow US URLs
		///</summary>
		[ImplementPropertyType("followUSURLs")]
		public string FollowUsurls
		{
			get { return GetFollowUsurls(this); }
		}

		/// <summary>Static getter for Follow US URLs</summary>
		public static string GetFollowUsurls(ISocialFollowUs that) { return that.GetPropertyValue<string>("followUSURLs"); }

		///<summary>
		/// LinkedIn: LinkedIn follow us URL
		///</summary>
		[ImplementPropertyType("linkedInFollowUSURL")]
		public string LinkedInFollowUsurl
		{
			get { return GetLinkedInFollowUsurl(this); }
		}

		/// <summary>Static getter for LinkedIn</summary>
		public static string GetLinkedInFollowUsurl(ISocialFollowUs that) { return that.GetPropertyValue<string>("linkedInFollowUSURL"); }

		///<summary>
		/// Twitter: Twitter follow us URL
		///</summary>
		[ImplementPropertyType("twitterFollowUSURL")]
		public string TwitterFollowUsurl
		{
			get { return GetTwitterFollowUsurl(this); }
		}

		/// <summary>Static getter for Twitter</summary>
		public static string GetTwitterFollowUsurl(ISocialFollowUs that) { return that.GetPropertyValue<string>("twitterFollowUSURL"); }

		///<summary>
		/// YouTube: YouTube Follow us URL
		///</summary>
		[ImplementPropertyType("youTubeFollowUSURL")]
		public string YouTubeFollowUsurl
		{
			get { return GetYouTubeFollowUsurl(this); }
		}

		/// <summary>Static getter for YouTube</summary>
		public static string GetYouTubeFollowUsurl(ISocialFollowUs that) { return that.GetPropertyValue<string>("youTubeFollowUSURL"); }
	}
}
