//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Subpage Banner Default</summary>
	[PublishedContentModel("subpageBannerDefault")]
	public partial class SubpageBannerDefault : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "subpageBannerDefault";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SubpageBannerDefault(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SubpageBannerDefault, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Drop Shadow
		///</summary>
		[ImplementPropertyType("defaultDropShadow")]
		public object DefaultDropShadow
		{
			get { return this.GetPropertyValue("defaultDropShadow"); }
		}

		///<summary>
		/// Subpage Banner Image: The "FullBanner" or "NarrowBanner" crop will be used for the selected image.
		///</summary>
		[ImplementPropertyType("DefaultSubPageBannerImage")]
		public IPublishedContent DefaultSubPageBannerImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("DefaultSubPageBannerImage"); }
		}
	}
}
